# Generated by Django 2.0.2 on 2018-06-08 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chatData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.TextField()),
                ('username', models.CharField(max_length=100)),
                ('text_content', models.TextField()),
                ('is_spam', models.BooleanField(default=False)),
            ],
        ),
    ]
